basics/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("student.urls", namespace='student'))
]

student/urls.py
from django.urls import path 
from student import views
from student.views import RoomDetail, RoomUpdateView, RoomDeleteView

app_name='student'

urlpatterns=[
    path("",views.home,name="home"),
    path("room/",views.room,name="room"),
    path("room/<int:pk>/", RoomDetail, name='room-detail'),
    path('room/<int:pk>/update', RoomUpdateView, name='room-update'),
    path('room/<int:pk>/delete', RoomDeleteView, name='room-delete'),
    # path("create-room/",views.createroom,name="create-room"),
    path("create-room/",views.Createroom, name="create-room"),

]

student/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    name=models.CharField(max_length=200)

    def __str__ (self):
     return f'name{self.name}'

class Room(models.Model):
    host=models.ForeignKey(User , on_delete=models.SET_NULL ,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name=models.CharField(max_length=200,null=True,blank=True)
    description=models.TextField(max_length=200,null=True,blank=True)
    update=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='user_created')
    def __str__ (self):
     return f'name{self.name},description{self.description},'

class Meso(models.Model):
    User=models.ForeignKey(User,on_delete=models.CASCADE)
    room=models.ForeignKey(Room,on_delete=models.CASCADE)
    body=models.TextField()
    update=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    def __str__ (self):
        return self.body[0:50]

student/forms.py
from django.forms import ModelForm
from .models import Room

class Roomform(ModelForm):

    class Meta:
        model=Room
        exclude = ('created_by',)

student/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Room
from .forms import Roomform
# Create your views here.

# rooms=[
#     {"id":1,"name":"its a python classroom"},
#     {"id":2,"name":"its a java classroom"},
#     {"id":3,"name":"its a web classroom"},
#     {"id":4,"name":"its a flutter classroom"}
# ]
def home(request):
    room=Room.objects.all()
    print(request.user)
    context={"room":room}

    return render(request,"home.html",context)

def room(request):
    room=Room.objects.all()
    context={"room":room}
    return render(request,"room.html",context)


def Createroom(request):
    form= Roomform()
    
    if request.method=="POST":
        form = Roomform(data=request.POST)
        
        if form.is_valid:
            #add created_by.. Who is the logged user
            form.instance.created_by = request.user
            form.save()
            return HttpResponseRedirect(reverse('student:home'))
        
    context={"form":form}

    return render(request,"forms.html",context)


def RoomDetail(request, pk):
    room = Room.objects.get(id=pk)

    context = {
        'room':room
    }
    return render(request, 'room-detail.html', context)

def RoomUpdateView(request, pk):
    room = get_object_or_404(Room, id=pk)

    form = Roomform(instance=room)

    if request.method == 'POST':
        form = Roomform(request.POST, instance=room)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('student:room-detail', kwargs={'pk':room.id}))

    context = {
        'form':form
    }
    return render(request, 'forms.html', context)

def RoomDeleteView(request, pk):
    room = get_object_or_404(Room, id=pk)

    if request.method == 'POST':
        room.delete()
        return HttpResponseRedirect(reverse('student:home'))
    
    context = {
        'room':room
    }

    return render(request, 'confirm-delete.html', context )

student/templates/confirm-delete.html
{% extends 'main.html' %}

{% block content %}

<h5>Are you sure you want to delete</h5><br>

<form action="" method="POST">{% csrf_token %}
    <button type="submit">Confirm</button>
    <button><a href="{% url 'student:room-detail' room.id %}">No</a></button>
</form>

{% endblock content %}

student/templates/forms.html
{% extends "main.html"%}

{% block content%}


<form action="" method="POST">{% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>
</form>

{%endblock%}

student/templates/home.html
    {%extends "main.html"%}
    {% block content%}
    <!-- <a href="/">LOGO</a> -->
    <h1>hello please welcome to our home page</h1>
    <a href="/">LOGO</a>
    <p>am kiash from karatina university please welcome to my portfolio as software developer as flutter for mobliles and django for backend</p>
<div>
    <a href="{% url 'student:create-room'%}"> Create room</a>
 
    <div>
        {% for room in room %}
        <span>@{{room.host.username}}
    {{room.topoic.name}}
        </span><hr>

<h5>{{room.id}}-- <a href="{% url 'student:room-detail' room.id %}">{{room.name}}</a> </h5>
<hr>
<form method="POST" action="">
    {% csrf_token%}
    {{form}}
    <input type="submit" value="submit">
    
    </form>
        {%endfor%}
    </div>
</div>
    {% endblock %}

student/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dmy Basics site</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

student/templates/nav.html
{% extends "main.html"%}

{% block content  %}

{% endblock %}

student/templates/room-detail.html
{%extends "main.html"%}


    {% block content%}
    
    <h1>please welcome to class room please</h1>
    <a href="/">Home</a>
    <div>
        <div>
            <h2>{{room.id}}-- <a href="">{{room.name}}</a></h2>
           <br>
           <p>{{ room.description }}</p>
           <br>
            <button><a href="{% url 'student:room-update' room.id %}">Update</a></button>
           <button type="submit"><a href="{% url 'student:room-delete' room.id %}">Delete</a></button>
        </div>
    </div>
    {% endblock %}

student/templates/room.html
{%extends "main.html"%}


    {% block content%}
    
    <h1>please welcome to class room please</h1>
    <a href="/">LOGO</a>
    <div>
        <div>
            {% for room in rooms %}
            <h6>{{room.id}}-- <a href="">{room.name}}</a>></h6>
            {%endfor%}
        </div>
    </div>
    {% endblock %}